import Head from "next/head";
import { Inter } from "next/font/google";

// Components
import Hero from "@/components/Hero";
import Header from "@/components/Header";
import Footer from "@/components/Footer";
import About from "@/components/About";
import SellingPoints from "@/components/SellingPoints";
import TextCarousel from "@/components/TextCarousel";
import ProductShowcase from "@/components/ProductShowcase";
import CommunityBanner from "@/components/CommunityBanner";
import News from "@/components/News";
import Productivity from "@/components/Productivity";

// Models
import { AboutSection, HeroSection, SellingPointsSection } from "@/models/Sections";
import { useEffect, useState } from "react";

export default function Home() {
	// Denna data kommer senare att hämtas från CMS och skickas in i sektionskomponenterna
	const heroSection: HeroSection = {
		boldText: "CAMELON-SAAS",
		lightText: " ÄR GRATIS",
		subText:
			"Lorem ipsum dolor sit amet, consectetur adipisicing elit. Iste, praesentium vero ipsam quis ad similique",
		callToAction: {
			url: "#about",
			text: "LÄS MER",
			target: "_self",
		},
	};

	const aboutSection: AboutSection = {
		title: "Kraftfull mjukvara \n gratis!",
		subText:
			"Lorem ipsum dolor, sit amet consectetur adipisicing elit. Praesentium minus cumque quam modi provident dicta facere soluta ab molestias eaque, alias sequi. Aliquid nostrum ut sit repudiandae incidunt, a tenetur? Lorem, ipsum dolor sit amet consectetur adipisicing elit. Deleniti",
		imageUrl: "/images/about/laptop.png",
	};

	const sellingPointsSection: SellingPointsSection = {
		title: "Funktioner",
		subText:
			"Lorem ipsum dolor, sit amet consectetur adipisicing elit. Praesentium minus cumque quam modi provident dicta facere soluta ab molestias eaque, alias sequi. Aliquid nostrum ut sit repudiandae incidunt, a tenetur?",
		sellingPoints: [
			{
				text: "HELT FLEXIBEL",
				imageUrl: "images/sellingPoints/flexible-icon.svg",
			},
			{
				text: "GRATIS NEDLADDNING",
				imageUrl: "images/sellingPoints/download-icon.svg",
			},
			{
				text: "MODERN DESIGN",
				imageUrl: "images/sellingPoints/design-icon.svg",
			},
			{
				text: "100% RESPONSIV",
				imageUrl: "images/sellingPoints/responsive-icon.svg",
			},
		],
	};

	return (
		<>
			<Header />
			<Head>
				<title>CamelonSaaS - Home Page</title>
				<meta name="description" content="Generated by create next app" />
			</Head>
			<main>
				<Hero {...heroSection} />
				<About {...aboutSection} />
				<SellingPoints {...sellingPointsSection} />
				<TextCarousel />
				<ProductShowcase />
				<CommunityBanner />
				<News />
				<Productivity />
			</main>
			<Footer />
		</>
	);
}
