import Head from 'next/head';
import { Inter } from 'next/font/google';

// Components
import Hero from '@/components/Hero';
import Header from '@/components/Header';
import Footer from '@/components/Footer';
import About from '@/components/About';
import SellingPoints from '@/components/SellingPoints';
import TextCarousel from '@/components/TextCarousel';
import ProductShowcase from '@/components/ProductShowcase';
import CommunityBanner from '@/components/CommunityBanner';
import News from '@/components/News';
import Productivity from '@/components/Productivity';

// Models
import { HeroSection } from '@/models/Sections';
import { useEffect, useState } from 'react';

export default function Home() {
	
  // Denna data kommer senare att hämtas från CMS och skickas in i sektionskomponenterna
  const heroSection: HeroSection = {
    boldText: 'CAMELON-SAAS',
    lighText: 'ÄR GRATIS',
    subText:
      'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Iste, praesentium vero ipsam quis ad similique',
    calToAction: {
      url: '#about',
      text: 'LÄS MER',
      target: '_self',
    },
  };

  return (
    <>
      <Header />
      <Head>
        <title>CamelonSaaS - Home Page</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <main>
        <Hero {...heroSection} />
        <About />
        <SellingPoints />
        <TextCarousel />
        <ProductShowcase />
        <CommunityBanner />
        <News />
        <Productivity />
      </main>
      <Footer />
    </>
  );
}
